baseURL = 'https://example.org/'
languageCode = 'en-gb'
title = 'Blog'

[params]
  description = 'My blog'
  author = 'Louis Van Steene'
  mainSections = ['posts']
  dateFormat = 'January 2, 2006'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 2
  [[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 3
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 4

[taxonomies]
  tag = 'tags'
  category = 'categories'

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
